import random as r
import time as t
def retry():
    print("[1]  YES")
    print("[2]  N0")
    rt = input("[IMP] USE AGAIN? ")
    if rt == "2":
        print("0k.....N0 Pr0blem ...Sed")
        exit()
    elif rt == "1":
        print("KooL")
        t.sleep(2)
        cal()
    else:
        print("Wrong Value.....Retry in 3 seconds")
        t.sleep(3)
        retry()
def banner():
    x = r.randint(0, 99999)
    y = str(x)
    print("______________________________")
    print("|         Blue  devil        |")
    print("|Telegram - t.me/AKASH_AM1   |")
    print("|Insta - @blue_devil_official|")
    print("|YT -                        |")
    print("|Subscribe &&  Li9ke         |")
    print(f"CURRENT ONLINE BOT USERS = {y}")
    print("------------------------------")
def cal():
    banner()
    print("------------------------------")
    print("|   Blue  devil Calculator   |")
    print("|   * = Multiplication       |")
    print("|   / = Division             |")
    print("|   + = Addition             |")
    print("|   - = Substraction         |")
    print("|   ** = To the Power        |")
    print("------------------------------")
    t.sleep(2)
    deed = input("What u want To do :  ")
    if deed == "*":
        a = input("FIRST NUMBER : ")
        b = input("SECOND NUMBER :")
        a1 = float(a)
        b1 = float(b)
        result = str(a1 * b1)
        print("So " + a + " x " + b + " = " + result + ".O")
        retry()
    elif deed == "/":
        a = input("FIRST NUMBER : ")
        b = input("SECOND NUMBER :")
        a1 = int(a)
        b1 = int(b)
        result = str(a1 / b1)
        print("so " + a + " / " + b + " = " + result + ".O")
        retry()
    elif deed == "+":
        a = input("FIRST NUMBER : ")
        b = input("SECOND NUMBER :")
        a1 = int(a)
        b1 = int(b)
        result = str(a1 + b1)
        print("so " + a + " + " + b + " = " + result + ".O")
        retry()
    elif deed == "-":
        a = input("FIRST NUMBER : ")
        b = input("SECOND NUMBER :")
        a1 = int(a)
        b1 = int(b)
        result = str(a1 - b1)
        print("so " + a + " - " + b + " = " + result + ".O")
        retry()
    elif deed == "**":
        a = input("FIRST NUMBER : ")
        b = input("SECOND NUMBER :")
        a1 = int(a)
        b1 = int(b)
        result = str(a1 ** b1)
        print("so " + a + " ** " + b + " = " + result)
        retry()
    else:
        print("              [ERROR] IT SEEMS THAT BU ENTERED A WRONG OPTION....xD")
        print("              [ERROR] THAT BLUE DEVIL CAN'T RECOGNISE\n              [ERROR] RETRY IN 3 SECONDS")
        t.sleep(4)
        cal()
cal()